02/08/2021 00:49:29|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/08/2021 00:49:29|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/08/2021 00:49:29|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/08/2021 00:49:29|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/08/2021 00:49:29|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/08/2021 00:57:40|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/08/2021 00:57:40|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/08/2021 00:57:40|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/08/2021 00:57:40|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/08/2021 00:57:40|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/08/2021 09:48:20|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/08/2021 09:48:20|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/08/2021 09:48:20|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/08/2021 09:48:20|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/08/2021 09:48:20|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/08/2021 12:07:31|INFO    |root                            |Using opensubtitlescom again after 10 minutes, (disabled because: ProviderError)|
02/08/2021 12:08:30|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:18, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:08:52|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:18, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:09:18|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:19, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:09:54|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:19, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:10:18|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:20, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:14:51|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:24, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:15:17|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:25, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:15:40|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:25, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:16:04|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c823a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:16:06|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:26, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:16:09|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d96f760>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:16:17|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b7d0340>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:16:33|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b988160>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:17:05|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d96f8b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:17:06|WARNING |retry.api                       |HTTPConnectionPool(host='s5.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c007880>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:17:11|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462670>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:17:15|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c4626a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:17:23|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462340>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:17:39|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:18:12|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:18:12|WARNING |retry.api                       |HTTPConnectionPool(host='s5.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462a90>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:18:17|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c823280>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:18:21|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887ba74e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:18:30|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:18:46|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462760>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:19:18|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462370>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:19:18|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75a550>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:19:23|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75aa60>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:19:31|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75aaf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:19:47|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75ae80>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:20:19|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75a130>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:20:20|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b75a940>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:20:25|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c823fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:20:29|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c0078b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:20:37|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9883a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:20:53|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462220>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:21:26|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c4620a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:21:26|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c462430>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:21:31|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c801340>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:21:35|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c801160>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:21:44|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c8019d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:22:00|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c801d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:22:32|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c801ee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:23:05|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:33, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:23:29|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:33, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:23:53|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:33, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:24:17|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:34, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:24:40|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 21/08/02 12:34, because of: ValueError. Exception info: "invalid literal for int() with base 10: ''"|
02/08/2021 12:25:23|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d2c3c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:25:27|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c00ffa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:25:36|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:25:52|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:26:24|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badfa90>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:26:24|WARNING |retry.api                       |HTTPConnectionPool(host='s104.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badfa60>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:26:29|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badff40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:26:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887babc100>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:26:42|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b988d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:26:58|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badfc40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:27:30|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf970>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:27:31|WARNING |retry.api                       |HTTPConnectionPool(host='s104.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf910>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:27:36|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf490>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:27:40|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf310>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:27:48|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf160>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:28:04|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:28:37|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baefbe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:28:37|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef310>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:28:41|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef2e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:28:50|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef580>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:29:06|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baefdf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:29:38|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887baef0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:29:38|WARNING |retry.api                       |HTTPConnectionPool(host='s1.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf700>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:29:43|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf100>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:29:48|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:29:56|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf400>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:30:12|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887badf820>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:39:59|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d08f250>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:40:03|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d0b3d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:40:11|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf76550>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:40:28|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c064c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:41:00|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bae5280>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:41:00|WARNING |retry.api                       |HTTPConnectionPool(host='s102.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b7237f0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:41:05|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b723f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:41:10|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c069d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:41:18|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957640>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:41:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9576d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:42:06|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957820>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:42:06|WARNING |retry.api                       |HTTPConnectionPool(host='s102.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d0b3cd0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:42:12|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957940>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:42:16|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:42:24|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:42:40|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:43:13|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bfb26d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:43:13|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b966820>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:43:17|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b966a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:43:25|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b966ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:43:42|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b966eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:44:14|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b949070>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:44:14|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9491c0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:44:19|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:44:24|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:44:32|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:44:48|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:45:20|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b7237f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:45:20|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b957d60>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:45:26|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9495b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:45:30|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b949730>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:45:38|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b949970>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:45:54|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b949b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:46:20|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: ValueError)|
02/08/2021 12:46:21|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b8004f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:46:26|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b8b2820>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:46:27|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9498e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:46:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf305b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:46:50|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf76f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:23|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b93cc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:23|WARNING |retry.api                       |HTTPConnectionPool(host='s4.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887ba6e520>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:47:28|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887ba6e400>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:32|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bacefa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:32|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887ba6e0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:36|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c00ff10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:41|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c00f310>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:44|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf3da30>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:47:57|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6d310>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:01|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6dfd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:29|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:29|WARNING |retry.api                       |HTTPConnectionPool(host='s4.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf3df40>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:48:33|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf3daf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:33|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf3dd60>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:48:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:38|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf637c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:39|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf637f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:43|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63460>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:47|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63250>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:48:51|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63190>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:03|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6d5e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:07|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6d7c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:35|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6dbb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:36|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bbdc6a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:39|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6d8e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:39|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6d910>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:49:40|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf63d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:45|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:48|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf6dbe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:49|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b370>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:49:57|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b670>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:04|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b520>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:13|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b880>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:37|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:37|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5b7f0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:50:45|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdca160>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:46|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5bbe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:49|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf5bbb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:50:57|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf3dd00>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:14|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d1326a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:14|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b5fce50>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:18|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b70b0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:27|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb50550>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:43|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb45d00>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:46|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d12cac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:46|WARNING |retry.api                       |HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb45cd0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:51:52|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb463a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:51:56|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb46520>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:04|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb466d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:15|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb45d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:15|WARNING |retry.api                       |HTTPConnectionPool(host='s104.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb469d0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:52:20|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb46820>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:21|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb46c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:25|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb46fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:33|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb76160>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:49|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb76340>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:52:53|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb46e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:53:25|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bb76400>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:53:25|WARNING |retry.api                       |HTTPConnectionPool(host='s104.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf8eee0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:53:30|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b988760>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:53:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdd2af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:53:43|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887da0e880>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:53:59|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d7a3700>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:54:31|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d7a3190>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:55:38|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b9345b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:55:43|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d08f610>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:55:47|ERROR   |root                            |BAZARR unable to sync subtitles: /data/media/tv/That '70s Show/Season 8/That '70s Show - S08E04 - Misfire Bluray-1080p.srt|
02/08/2021 12:55:51|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b723400>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:56:07|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887cfdb3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:56:39|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c003f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:56:40|WARNING |retry.api                       |HTTPConnectionPool(host='s5.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdfcc70>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:56:45|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdfa190>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:56:49|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdfa370>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:56:58|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdfa6d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:57:18|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdfa910>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:57:19|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/08/2021 12:57:50|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9baf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:57:51|WARNING |retry.api                       |HTTPConnectionPool(host='s5.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d0c8070>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 12:57:56|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b805ee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:58:00|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d1121c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:58:08|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d1122e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:58:24|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9b220>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:58:57|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9bc40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:59:21|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdd95e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:59:26|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bdffa60>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:59:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bc46ac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 12:59:50|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b698310>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:00:22|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b698220>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:04:40|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/08/2021 13:05:34|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bc42250>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:05:38|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887da3e0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:05:46|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b8c8790>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:06:02|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b692dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:06:35|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b6926d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:06:35|WARNING |retry.api                       |HTTPConnectionPool(host='s106.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b692e20>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 13:06:40|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9ea30>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:06:44|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9e0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:06:52|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9e370>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:07:09|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9e5b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:07:41|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9e040>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:07:41|WARNING |retry.api                       |HTTPConnectionPool(host='s106.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9ed30>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 13:07:46|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b692eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:07:51|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b6920a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:07:59|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:08:15|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bf9e220>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:08:47|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887d2c3130>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:10:47|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887cfd0400>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:10:51|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b6922b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:10:59|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b692bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:11:16|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bc42b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:11:48|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bd84af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:11:48|WARNING |retry.api                       |HTTPConnectionPool(host='s106.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887cfd57c0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 13:11:53|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c08b4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:11:57|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c08b550>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:12:06|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887bd847c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:12:22|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b692cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:12:54|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b800550>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:12:54|WARNING |retry.api                       |HTTPConnectionPool(host='s106.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887b800490>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...|
02/08/2021 13:12:59|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887ba10730>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:13:04|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887cfd5460>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:13:12|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:13:28|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:14:00|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:14:01|WARNING |urllib3.connectionpool          |Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c0730a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:14:05|WARNING |urllib3.connectionpool          |Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073280>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:14:13|WARNING |urllib3.connectionpool          |Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c08b250>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:14:30|WARNING |urllib3.connectionpool          |Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073670>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:15:02|WARNING |urllib3.connectionpool          |Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f887c073c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /|
02/08/2021 13:15:35|WARNING |retry.api                       |HTTPSConnectionPool(host='api.betaseries.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/08/2021 13:15:59|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/08/2021 15:07:31|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/08/2021 15:46:20|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
